kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  real-ip-header: X-Forwarded-For
  real-ip-recursive: "True"
  set-real-ip-from: 172.16.1.0/24,192.168.1.0/24

